package com.gu.source.paparazzigen.processor

import com.gu.source.paparazzigen.RenderMode
import com.gu.source.paparazzigen.TestDevice
import com.gu.source.paparazzigen.TestFontScale
import com.gu.source.paparazzigen.TestNightMode
import com.gu.source.paparazzigen.TestOrientation
import kotlin.test.Test
import kotlin.test.assertEquals

private const val PACKAGE = "com.gu.source.components"

class TestFileGeneratorTest {
    @Test
    fun `default config parameterises only night mode and needs no screenshot filter`() {
        val generated = generate(TestConfig())

        assertEquals(
            """
            |// Generated by paparazzigen. Do not edit.
            |// Regenerate by running the paparazzi record or verify task for this module.
            |package com.gu.source.components
            |
            |import app.cash.paparazzi.Paparazzi
            |import com.android.resources.NightMode
            |import com.google.testing.junit.testparameterinjector.TestParameter
            |import com.google.testing.junit.testparameterinjector.TestParameterInjector
            |import com.gu.source.utils.paparazzi.BaseDeviceConfig
            |import com.gu.source.utils.paparazzi.FontScale
            |import com.gu.source.utils.paparazzi.Orientation
            |import com.gu.source.utils.paparazzi.createComponentPaparazziRule
            |import com.gu.source.utils.paparazzi.toDeviceConfig
            |import org.junit.Rule
            |import org.junit.Test
            |import org.junit.runner.RunWith
            |
            |@RunWith(TestParameterInjector::class)
            |public class CoreButtonPaparazziTest(
            |  @TestParameter
            |  private val nightMode: NightMode,
            |) {
            |  @get:Rule
            |  public val paparazzi: Paparazzi = createComponentPaparazziRule(
            |        deviceConfig = BaseDeviceConfig.Phone.toDeviceConfig(
            |          nightMode = nightMode,
            |          fontScale = FontScale.Normal,
            |          orientation = Orientation.Portrait,
            |        ),
            |      )
            |
            |  @Test
            |  public fun coreButton() {
            |    paparazzi.snapshot {
            |      CoreButtonPreview()
            |    }
            |  }
            |}
            |
            """.trimMargin(),
            generated,
        )
    }

    @Test
    fun `every axis set to all is parameterised and filters screenshots`() {
        val generated = generate(
            TestConfig(
                nightMode = TestNightMode.All,
                device = TestDevice.All,
                fontScale = TestFontScale.All,
                orientation = TestOrientation.All,
            ),
        )

        assertEquals(ALL_AXES_EXPECTED, generated)
    }

    @Test
    fun `fully pinned screen config has no runner, constructor or filter`() {
        val generated = generate(
            TestConfig(
                nightMode = TestNightMode.Night,
                device = TestDevice.Tablet,
                fontScale = TestFontScale.ExtraLarge,
                orientation = TestOrientation.Landscape,
                renderMode = RenderMode.Screen,
            ),
        )

        assertEquals(
            """
            |// Generated by paparazzigen. Do not edit.
            |// Regenerate by running the paparazzi record or verify task for this module.
            |package com.gu.source.components
            |
            |import app.cash.paparazzi.Paparazzi
            |import com.android.resources.NightMode
            |import com.gu.source.utils.paparazzi.BaseDeviceConfig
            |import com.gu.source.utils.paparazzi.FontScale
            |import com.gu.source.utils.paparazzi.Orientation
            |import com.gu.source.utils.paparazzi.createScreenPaparazziRule
            |import com.gu.source.utils.paparazzi.toDeviceConfig
            |import org.junit.Rule
            |import org.junit.Test
            |
            |public class CoreButtonPaparazziTest {
            |  @get:Rule
            |  public val paparazzi: Paparazzi = createScreenPaparazziRule(
            |        deviceConfig = BaseDeviceConfig.Tablet.toDeviceConfig(
            |          nightMode = NightMode.NIGHT,
            |          fontScale = FontScale.ExtraLarge,
            |          orientation = Orientation.Landscape,
            |        ),
            |      )
            |
            |  @Test
            |  public fun coreButton() {
            |    paparazzi.snapshot {
            |      CoreButtonPreview()
            |    }
            |  }
            |}
            |
            """.trimMargin(),
            generated,
        )
    }

    @Test
    fun `day only config is not parameterised and pins the night mode`() {
        val generated = generate(TestConfig(nightMode = TestNightMode.Day))

        assertEquals(
            false,
            generated.contains("TestParameterInjector"),
        )
        assertEquals(true, generated.contains("nightMode = NightMode.NOTNIGHT"))
        assertEquals(false, generated.contains("filterScreenshots"))
    }

    @Test
    fun `a file with several configs generates a class per config`() {
        val file = TestFile(
            packageName = PACKAGE,
            fileName = "CoreButtonPaparazziTest",
            classes = listOf(
                TestClass(
                    className = "CoreButtonPaparazziTest",
                    config = TestConfig(),
                    previews = listOf(PreviewFunction("CoreButtonPreview", "coreButton")),
                ),
                TestClass(
                    className = "CoreButtonPaparazziTestTablet",
                    config = TestConfig(device = TestDevice.Tablet),
                    previews = listOf(PreviewFunction("CoreButtonWidePreview", "coreButtonWide")),
                ),
            ),
        )

        val generated = file.toFileSpec().toString()

        assertEquals(true, generated.contains("public class CoreButtonPaparazziTest("))
        assertEquals(true, generated.contains("public class CoreButtonPaparazziTestTablet("))
        assertEquals(true, generated.contains("BaseDeviceConfig.Phone.toDeviceConfig("))
        assertEquals(true, generated.contains("BaseDeviceConfig.Tablet.toDeviceConfig("))
        assertEquals(true, generated.contains("public fun coreButton()"))
        assertEquals(true, generated.contains("public fun coreButtonWide()"))
    }

    @Test
    fun `several previews sharing a config generate several tests in one class`() {
        val file = TestFile(
            packageName = PACKAGE,
            fileName = "CoreButtonPaparazziTest",
            classes = listOf(
                TestClass(
                    className = "CoreButtonPaparazziTest",
                    config = TestConfig(),
                    previews = listOf(
                        PreviewFunction("CoreButtonPreview", "coreButton"),
                        PreviewFunction("CoreButtonIconPreview", "coreButtonIcon"),
                    ),
                ),
            ),
        )

        val generated = file.toFileSpec().toString()

        assertEquals(1, Regex("public class ").findAll(generated).count())
        assertEquals(true, generated.contains("CoreButtonPreview()"))
        assertEquals(true, generated.contains("CoreButtonIconPreview()"))
    }
}

private fun generate(config: TestConfig): String = TestFile(
    packageName = PACKAGE,
    fileName = "CoreButtonPaparazziTest",
    classes = listOf(
        TestClass(
            className = "CoreButtonPaparazziTest",
            config = config,
            previews = listOf(PreviewFunction("CoreButtonPreview", "coreButton")),
        ),
    ),
).toFileSpec().toString()

private val ALL_AXES_EXPECTED = """
    |// Generated by paparazzigen. Do not edit.
    |// Regenerate by running the paparazzi record or verify task for this module.
    |package com.gu.source.components
    |
    |import app.cash.paparazzi.Paparazzi
    |import com.android.resources.NightMode
    |import com.google.testing.junit.testparameterinjector.TestParameter
    |import com.google.testing.junit.testparameterinjector.TestParameterInjector
    |import com.gu.source.utils.paparazzi.BaseDeviceConfig
    |import com.gu.source.utils.paparazzi.FontScale
    |import com.gu.source.utils.paparazzi.Orientation
    |import com.gu.source.utils.paparazzi.createComponentPaparazziRule
    |import com.gu.source.utils.paparazzi.filterScreenshots
    |import com.gu.source.utils.paparazzi.toDeviceConfig
    |import org.junit.Before
    |import org.junit.Rule
    |import org.junit.Test
    |import org.junit.runner.RunWith
    |
    |@RunWith(TestParameterInjector::class)
    |public class CoreButtonPaparazziTest(
    |  @TestParameter
    |  private val nightMode: NightMode,
    |  @TestParameter
    |  private val deviceConfig: BaseDeviceConfig,
    |  @TestParameter
    |  private val fontScale: FontScale,
    |  @TestParameter
    |  private val orientation: Orientation,
    |) {
    |  @get:Rule
    |  public val paparazzi: Paparazzi = createComponentPaparazziRule(
    |        deviceConfig = deviceConfig.toDeviceConfig(
    |          nightMode = nightMode,
    |          fontScale = fontScale,
    |          orientation = orientation,
    |        ),
    |      )
    |
    |  @Before
    |  public fun applyScreenshotFilters() {
    |    filterScreenshots(
    |      nightMode = nightMode,
    |      deviceConfig = deviceConfig,
    |      fontScale = fontScale,
    |      orientation = orientation,
    |    )
    |  }
    |
    |  @Test
    |  public fun coreButton() {
    |    paparazzi.snapshot {
    |      CoreButtonPreview()
    |    }
    |  }
    |}
    |
""".trimMargin()