package com.gu.source.paparazzigen.processor

import com.gu.source.paparazzigen.RenderMode
import com.gu.source.paparazzigen.TestDevice
import com.gu.source.paparazzigen.TestFontScale
import com.gu.source.paparazzigen.TestNightMode
import com.gu.source.paparazzigen.TestOrientation
import com.squareup.kotlinpoet.AnnotationSpec
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.MemberName
import com.squareup.kotlinpoet.ParameterSpec
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeSpec

private const val PAPARAZZI_PACKAGE = "com.gu.source.utils.paparazzi"
private const val INJECTOR_PACKAGE = "com.google.testing.junit.testparameterinjector"
private const val JUNIT_PACKAGE = "org.junit"

private val paparazzi = ClassName("app.cash.paparazzi", "Paparazzi")
private val nightModeClass = ClassName("com.android.resources", "NightMode")
private val baseDeviceConfig = ClassName(PAPARAZZI_PACKAGE, "BaseDeviceConfig")
private val fontScaleClass = ClassName(PAPARAZZI_PACKAGE, "FontScale")
private val orientationClass = ClassName(PAPARAZZI_PACKAGE, "Orientation")
private val testParameter = ClassName(INJECTOR_PACKAGE, "TestParameter")
private val testParameterInjector = ClassName(INJECTOR_PACKAGE, "TestParameterInjector")
private val runWith = ClassName("org.junit.runner", "RunWith")
private val rule = ClassName(JUNIT_PACKAGE, "Rule")
private val test = ClassName(JUNIT_PACKAGE, "Test")
private val before = ClassName(JUNIT_PACKAGE, "Before")

private val componentRule = MemberName(PAPARAZZI_PACKAGE, "createComponentPaparazziRule")
private val screenRule = MemberName(PAPARAZZI_PACKAGE, "createScreenPaparazziRule")
private val toDeviceConfig = MemberName(PAPARAZZI_PACKAGE, "toDeviceConfig", isExtension = true)
private val filterScreenshots = MemberName(PAPARAZZI_PACKAGE, "filterScreenshots")

private const val NIGHT_MODE_PARAM = "nightMode"
private const val DEVICE_PARAM = "deviceConfig"
private const val FONT_SCALE_PARAM = "fontScale"
private const val ORIENTATION_PARAM = "orientation"

/** Builds the KotlinPoet [FileSpec] for a generated test file. */
internal fun TestFile.toFileSpec(): FileSpec {
    val builder = FileSpec.builder(packageName, fileName)
        .addFileComment(
            "Generated by paparazzigen. Do not edit.\n" +
                "Regenerate by running the paparazzi record or verify task for this module.",
        )
    classes.forEach {
        builder.addType(it.toTypeSpec(packageName))
    }
    return builder.build()
}

private fun TestClass.toTypeSpec(packageName: String): TypeSpec {
    val classBuilder = TypeSpec.classBuilder(className)

    // Create constructor with test parameters, if needed.
    if (config.isParameterised) {
        classBuilder.addAnnotation(
            AnnotationSpec.builder(runWith)
                .addMember("%T::class", testParameterInjector)
                .build(),
        )

        val constructor = FunSpec.constructorBuilder()

        config.parameters().forEach { (name, type) ->
            constructor.addParameter(
                ParameterSpec.builder(name, type)
                    .addAnnotation(testParameter)
                    .build(),
            )
            classBuilder.addProperty(
                PropertySpec.builder(name, type, KModifier.PRIVATE)
                    .initializer(name)
                    .build(),
            )
        }
        classBuilder.primaryConstructor(constructor.build())
    }

    // Add paparazzi rule
    classBuilder.addProperty(paparazziRule(config))

    if (config.needsScreenshotFilter) {
        // Add a @Before function to filter screenshots for this test class.
        classBuilder.addFunction(filterFunction(config))
    }

    // Add a test function for each preview.
    previews.forEach { classBuilder.addFunction(it.toFunSpec(packageName)) }

    return classBuilder.build()
}

private fun TestConfig.parameters(): List<Pair<String, ClassName>> = buildList {
    if (nightMode == TestNightMode.All) {
        add(NIGHT_MODE_PARAM to nightModeClass)
    }

    if (device == TestDevice.All) {
        add(DEVICE_PARAM to baseDeviceConfig)
    }

    if (fontScale == TestFontScale.All) {
        add(FONT_SCALE_PARAM to fontScaleClass)
    }

    if (orientation == TestOrientation.All) {
        add(ORIENTATION_PARAM to orientationClass)
    }
}

private fun paparazziRule(config: TestConfig): PropertySpec {
    val factory = when (config.renderMode) {
        RenderMode.Component -> componentRule
        RenderMode.Screen -> screenRule
    }
    val initializer = CodeBlock.builder()
        .add("%M(\n", factory)
        .indent()
        .add("deviceConfig·=·%L.%M(\n", config.deviceExpression(), toDeviceConfig)
        .indent()
        .add("nightMode·=·%L,\n", config.nightModeExpression())
        .add("fontScale·=·%L,\n", config.fontScaleExpression())
        .add("orientation·=·%L,\n", config.orientationExpression())
        .unindent()
        .add("),\n")
        .unindent()
        .add(")")
        .build()

    return PropertySpec.builder("paparazzi", paparazzi)
        .addAnnotation(
            AnnotationSpec.builder(rule).useSiteTarget(AnnotationSpec.UseSiteTarget.GET).build(),
        )
        .initializer(initializer)
        .build()
}

private fun filterFunction(config: TestConfig): FunSpec {
    val body = CodeBlock.builder()
        .add("%M(\n", filterScreenshots)
        .indent()
        .add("nightMode·=·%L,\n", config.nightModeExpression())
        .add("deviceConfig·=·%L,\n", config.deviceExpression())
        .add("fontScale·=·%L,\n", config.fontScaleExpression())
        .add("orientation·=·%L,\n", config.orientationExpression())
        .unindent()
        .add(")\n")
        .build()

    return FunSpec.builder("applyScreenshotFilters")
        .addAnnotation(before)
        .addCode(body)
        .build()
}

private fun PreviewFunction.toFunSpec(packageName: String) = FunSpec.builder(testName)
    .addAnnotation(test)
    .addCode(
        CodeBlock.builder()
            .beginControlFlow("paparazzi.snapshot")
            // TODO: 14/08/2026 Later: add optional support for wrapping in `AppColourMode` 
            .addStatement("%M()", MemberName(packageName, functionName))
            .endControlFlow()
            .build(),
    )
    .build()

private fun TestConfig.deviceExpression(): CodeBlock = when (device) {
    TestDevice.All -> CodeBlock.of("%L", DEVICE_PARAM)
    TestDevice.Phone -> CodeBlock.of("%T.Phone", baseDeviceConfig)
    TestDevice.Tablet -> CodeBlock.of("%T.Tablet", baseDeviceConfig)
}

private fun TestConfig.nightModeExpression(): CodeBlock = when (nightMode) {
    TestNightMode.All -> CodeBlock.of("%L", NIGHT_MODE_PARAM)
    TestNightMode.Day -> CodeBlock.of("%T.NOTNIGHT", nightModeClass)
    TestNightMode.Night -> CodeBlock.of("%T.NIGHT", nightModeClass)
}

private fun TestConfig.fontScaleExpression(): CodeBlock = when (fontScale) {
    TestFontScale.All -> CodeBlock.of("%L", FONT_SCALE_PARAM)
    TestFontScale.Normal -> CodeBlock.of("%T.Normal", fontScaleClass)
    TestFontScale.ExtraLarge -> CodeBlock.of("%T.ExtraLarge", fontScaleClass)
}

private fun TestConfig.orientationExpression(): CodeBlock = when (orientation) {
    TestOrientation.All -> CodeBlock.of("%L", ORIENTATION_PARAM)
    TestOrientation.Portrait -> CodeBlock.of("%T.Portrait", orientationClass)
    TestOrientation.Landscape -> CodeBlock.of("%T.Landscape", orientationClass)
}