name: Android Docs

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    name: Check for Android changes
    runs-on: ubuntu-latest
    if: github.repository == 'guardian/source-apps'
    permissions:
      pull-requests: read
    outputs:
      android: ${{ steps.filter.outputs.android }}
    steps:
    - uses: actions/checkout@v5
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          android:
            - 'android/**'
            - '.github/**'          

  docs:
    name: Generate Android docs
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.android == 'true' && github.repository == 'guardian/source-apps' }}
    permissions: write-all

    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.GU_ANDROID_CLIENT_ID }}
          private-key: ${{ secrets.GU_ANDROID_PRIVATE_KEY }}
          permission-contents: write

      - uses: actions/checkout@v5
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Get GitHub App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: Build and commit docs
        run: |
          cd android
          ./gradlew :source:dokkaGeneratePublicationHtml --no-configuration-cache --rerun-tasks --no-build-cache
          git config --global user.name "${{ steps.app-token.outputs.app-slug }}[bot]"
          git config --global user.email "${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com"
          git fetch origin gh-pages
          git checkout gh-pages
          git pull origin gh-pages
          rm -rf docs
          mkdir -p docs
          mv source/build/dokka/html/* docs/
          git add docs
          git diff --staged --quiet || git commit -m "Update docs" -- docs
          git push origin gh-pages --set-upstream