name: Android Docs

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    name: Check for Android changes
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      android: ${{ steps.filter.outputs.android }}
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          android:
            - 'android/**'
            - '.github/**'          

  build:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.android == 'true' }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3


      - name: Build and generate docs
        run: |
          cd android
          ./gradlew :source:dokkaGfm --no-configuration-cache
          rm -rf docs
          mkdir -p docs
          mv source/build/dokka/gfm/* docs/
                    
      - name: Commit and push changes
        run: |
          git rev-parse --quiet --verify refs/heads/gh-pages >/dev/null && exists=true || exists=false
          if $exists; then git checkout gh-pages; else git checkout -b gh-pages; fi
          git add android/docs
          git commit -m "Update docs" -- docs
          git push origin gh-pages --set-upstream
          