name: Update Dependency Graph for Gradle
on:
  push:
    branches:
      - main
  workflow_dispatch: 
jobs:
  dependency-graph:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        id: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Set up Java
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Submit dependencies
        id: submit
        uses: gradle/actions/dependency-submission@b128da9bf0c2651a9fe51856df98ba6e611afc58 # v4.1.0
        with:
          build-root-directory: android

      - name: Log snapshot for user validation
        id: validate
        run: cat
          /home/runner/work/source-apps/source-apps/dependency-graph-reports/update_dependency_graph_for_gradle-dependency-graph.json
          | jq

    permissions:
      contents: write